package com.dao;

import com.vo.CheckboxAnswerCount;
import com.vo.CheckboxAnswerCountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckboxAnswerCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkbox_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(CheckboxAnswerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkbox_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(CheckboxAnswerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkbox_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String checkboxAnswerCountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkbox_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(CheckboxAnswerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkbox_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(CheckboxAnswerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkbox_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<CheckboxAnswerCount> selectByExample(CheckboxAnswerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkbox_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    CheckboxAnswerCount selectByPrimaryKey(String checkboxAnswerCountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkbox_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") CheckboxAnswerCount record, @Param("example") CheckboxAnswerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkbox_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") CheckboxAnswerCount record, @Param("example") CheckboxAnswerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkbox_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(CheckboxAnswerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkbox_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(CheckboxAnswerCount record);
}