package com.dao;

import com.vo.DesignCheckbox;
import com.vo.DesignCheckboxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DesignCheckboxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(DesignCheckboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(DesignCheckboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String designCheckboxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(DesignCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(DesignCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<DesignCheckbox> selectByExample(DesignCheckboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    DesignCheckbox selectByPrimaryKey(String designCheckboxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") DesignCheckbox record, @Param("example") DesignCheckboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") DesignCheckbox record, @Param("example") DesignCheckboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(DesignCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(DesignCheckbox record);
}