package com.dao;

import com.vo.DesignTemplet;
import com.vo.DesignTempletExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DesignTempletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    int countByExample(DesignTempletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    int deleteByExample(DesignTempletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    int deleteByPrimaryKey(String designTempletId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    int insert(DesignTemplet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    int insertSelective(DesignTemplet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    List<DesignTemplet> selectByExample(DesignTempletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    DesignTemplet selectByPrimaryKey(String designTempletId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") DesignTemplet record, @Param("example") DesignTempletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    int updateByExample(@Param("record") DesignTemplet record, @Param("example") DesignTempletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    int updateByPrimaryKeySelective(DesignTemplet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    int updateByPrimaryKey(DesignTemplet record);
}