package com.dao;

import com.vo.DesignText;
import com.vo.DesignTextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DesignTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_text
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(DesignTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_text
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(DesignTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_text
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String designTextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_text
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(DesignText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_text
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(DesignText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_text
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<DesignText> selectByExample(DesignTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_text
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    DesignText selectByPrimaryKey(String designTextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_text
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") DesignText record, @Param("example") DesignTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_text
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") DesignText record, @Param("example") DesignTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_text
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(DesignText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_text
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(DesignText record);
}