package com.dao;

import com.vo.DesignSingleOption;
import com.vo.DesignSingleOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DesignSingleOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(DesignSingleOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(DesignSingleOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String designSingleOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(DesignSingleOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(DesignSingleOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<DesignSingleOption> selectByExample(DesignSingleOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    DesignSingleOption selectByPrimaryKey(String designSingleOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") DesignSingleOption record, @Param("example") DesignSingleOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") DesignSingleOption record, @Param("example") DesignSingleOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(DesignSingleOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(DesignSingleOption record);
}