package com.dao;

import com.vo.DesignCheckboxOption;
import com.vo.DesignCheckboxOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DesignCheckboxOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(DesignCheckboxOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(DesignCheckboxOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String designCheckboxOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(DesignCheckboxOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(DesignCheckboxOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<DesignCheckboxOption> selectByExample(DesignCheckboxOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    DesignCheckboxOption selectByPrimaryKey(String designCheckboxOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") DesignCheckboxOption record, @Param("example") DesignCheckboxOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") DesignCheckboxOption record, @Param("example") DesignCheckboxOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(DesignCheckboxOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_checkbox_option
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(DesignCheckboxOption record);
}