package com.dao;

import com.vo.DesignSingle;
import com.vo.DesignSingleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DesignSingleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(DesignSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(DesignSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String designSingleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(DesignSingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(DesignSingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<DesignSingle> selectByExample(DesignSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    DesignSingle selectByPrimaryKey(String designSingleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") DesignSingle record, @Param("example") DesignSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") DesignSingle record, @Param("example") DesignSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(DesignSingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(DesignSingle record);
}