package com.dao;

import com.vo.DictSingle;
import com.vo.DictSingleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictSingleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(DictSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(DictSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String dictSingleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(DictSingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(DictSingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<DictSingle> selectByExample(DictSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    DictSingle selectByPrimaryKey(String dictSingleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictSingle record, @Param("example") DictSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") DictSingle record, @Param("example") DictSingleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(DictSingle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_single
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(DictSingle record);
}