package com.dao;

import com.vo.DictTemplet;
import com.vo.DictTempletExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictTempletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(DictTempletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(DictTempletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String dictTempletId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(DictTemplet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(DictTemplet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<DictTemplet> selectByExample(DictTempletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    DictTemplet selectByPrimaryKey(String dictTempletId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictTemplet record, @Param("example") DictTempletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") DictTemplet record, @Param("example") DictTempletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(DictTemplet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(DictTemplet record);
}