package com.dao;

import com.vo.DictTempletIndex;
import com.vo.DictTempletIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictTempletIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet_index
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(DictTempletIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet_index
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(DictTempletIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet_index
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String dictTempletIndexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet_index
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(DictTempletIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet_index
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(DictTempletIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet_index
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<DictTempletIndex> selectByExample(DictTempletIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet_index
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    DictTempletIndex selectByPrimaryKey(String dictTempletIndexId);

    /*获取dict_templet_index表数据，首先按照dict_templet_index_sign升序排序，然后按照dict_templet_index_order升序排序*/
    List<DictTempletIndex> selectByDictTempletIndexIdOrderByDictTempletIndexSignDictTempletIndexOrder(String dictTempletId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet_index
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictTempletIndex record, @Param("example") DictTempletIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet_index
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") DictTempletIndex record, @Param("example") DictTempletIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet_index
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(DictTempletIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_templet_index
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(DictTempletIndex record);
}