package com.dao;

import com.vo.DictCheckbox;
import com.vo.DictCheckboxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictCheckboxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(DictCheckboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(DictCheckboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String dictCheckboxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(DictCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(DictCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<DictCheckbox> selectByExample(DictCheckboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    DictCheckbox selectByPrimaryKey(String dictCheckboxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictCheckbox record, @Param("example") DictCheckboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") DictCheckbox record, @Param("example") DictCheckboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(DictCheckbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(DictCheckbox record);
}