package com.dao;

import com.vo.SingleAnswer;
import com.vo.SingleAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SingleAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    int countByExample(SingleAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    int deleteByExample(SingleAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    int deleteByPrimaryKey(String singleAnswerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    int insert(SingleAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    int insertSelective(SingleAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    List<SingleAnswer> selectByExample(SingleAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    SingleAnswer selectByPrimaryKey(String singleAnswerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SingleAnswer record, @Param("example") SingleAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    int updateByExample(@Param("record") SingleAnswer record, @Param("example") SingleAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    int updateByPrimaryKeySelective(SingleAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    int updateByPrimaryKey(SingleAnswer record);
}