package com.dao;

import com.vo.SingleAnswerCount;
import com.vo.SingleAnswerCountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SingleAnswerCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(SingleAnswerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(SingleAnswerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String singleAnswerCountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(SingleAnswerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(SingleAnswerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<SingleAnswerCount> selectByExample(SingleAnswerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    SingleAnswerCount selectByPrimaryKey(String singleAnswerCountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") SingleAnswerCount record, @Param("example") SingleAnswerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") SingleAnswerCount record, @Param("example") SingleAnswerCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(SingleAnswerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(SingleAnswerCount record);
}