package com.dao;

import com.vo.Sort;
import com.vo.SortExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String sortId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<Sort> selectByExample(SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    Sort selectByPrimaryKey(String sortId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sort record, @Param("example") SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") Sort record, @Param("example") SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(Sort record);
}