package com.dao;

import com.vo.UserLoginResult;
import com.vo.UserLoginResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserLoginResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_result
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(UserLoginResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_result
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(UserLoginResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_result
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String userLoginResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_result
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(UserLoginResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_result
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(UserLoginResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_result
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<UserLoginResult> selectByExample(UserLoginResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_result
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    UserLoginResult selectByPrimaryKey(String userLoginResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_result
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserLoginResult record, @Param("example") UserLoginResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_result
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") UserLoginResult record, @Param("example") UserLoginResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_result
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(UserLoginResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_result
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(UserLoginResult record);
}