package com.dao;

import com.vo.UserOperateLog;
import com.vo.UserOperateLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String userOperateLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(UserOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(UserOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<UserOperateLog> selectByExample(UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    UserOperateLog selectByPrimaryKey(String userOperateLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserOperateLog record, @Param("example") UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") UserOperateLog record, @Param("example") UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(UserOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(UserOperateLog record);
    
    List<UserOperateLog> selectOrderByUserOperateTime();
    
}