package com.dao;

import com.vo.UserLoginLog;
import com.vo.UserLoginLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int countByExample(UserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByExample(UserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int deleteByPrimaryKey(String userLoginLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insert(UserLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int insertSelective(UserLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    List<UserLoginLog> selectByExample(UserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    UserLoginLog selectByPrimaryKey(String userLoginLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserLoginLog record, @Param("example") UserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByExample(@Param("record") UserLoginLog record, @Param("example") UserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(UserLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Sun Mar 25 19:58:56 CST 2018
     */
    int updateByPrimaryKey(UserLoginLog record);
    
    List<UserLoginLog> selectOrderByuserLoginTime();
    
}