package com.vo;

public class CheckboxAnswerCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkbox_answer_count.checkbox_answer_count_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String checkboxAnswerCountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkbox_answer_count.checkbox_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Integer checkboxAnswerCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkbox_answer_count.design_checkbox_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String designCheckboxOptionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkbox_answer_count.checkbox_answer_count_id
     *
     * @return the value of checkbox_answer_count.checkbox_answer_count_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getCheckboxAnswerCountId() {
        return checkboxAnswerCountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkbox_answer_count.checkbox_answer_count_id
     *
     * @param checkboxAnswerCountId the value for checkbox_answer_count.checkbox_answer_count_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setCheckboxAnswerCountId(String checkboxAnswerCountId) {
        this.checkboxAnswerCountId = checkboxAnswerCountId == null ? null : checkboxAnswerCountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkbox_answer_count.checkbox_answer_count
     *
     * @return the value of checkbox_answer_count.checkbox_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Integer getCheckboxAnswerCount() {
        return checkboxAnswerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkbox_answer_count.checkbox_answer_count
     *
     * @param checkboxAnswerCount the value for checkbox_answer_count.checkbox_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setCheckboxAnswerCount(Integer checkboxAnswerCount) {
        this.checkboxAnswerCount = checkboxAnswerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkbox_answer_count.design_checkbox_option_id
     *
     * @return the value of checkbox_answer_count.design_checkbox_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDesignCheckboxOptionId() {
        return designCheckboxOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkbox_answer_count.design_checkbox_option_id
     *
     * @param designCheckboxOptionId the value for checkbox_answer_count.design_checkbox_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignCheckboxOptionId(String designCheckboxOptionId) {
        this.designCheckboxOptionId = designCheckboxOptionId == null ? null : designCheckboxOptionId.trim();
    }
}