package com.vo;

public class DesignSingle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_single.design_single_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String designSingleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_single.design_single_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String designSingleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_single.design_single_id
     *
     * @return the value of design_single.design_single_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDesignSingleId() {
        return designSingleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_single.design_single_id
     *
     * @param designSingleId the value for design_single.design_single_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignSingleId(String designSingleId) {
        this.designSingleId = designSingleId == null ? null : designSingleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_single.design_single_content
     *
     * @return the value of design_single.design_single_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDesignSingleContent() {
        return designSingleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_single.design_single_content
     *
     * @param designSingleContent the value for design_single.design_single_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignSingleContent(String designSingleContent) {
        this.designSingleContent = designSingleContent == null ? null : designSingleContent.trim();
    }
}