package com.vo;

public class DesignCheckboxOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_checkbox_option.design_checkbox_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String designCheckboxOptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_checkbox_option.design_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String designCheckboxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_checkbox_option.design_checkbox_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Integer designCheckboxOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_checkbox_option.design_checkbox_option_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String designCheckboxOptionContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_checkbox_option.design_checkbox_option_id
     *
     * @return the value of design_checkbox_option.design_checkbox_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDesignCheckboxOptionId() {
        return designCheckboxOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_checkbox_option.design_checkbox_option_id
     *
     * @param designCheckboxOptionId the value for design_checkbox_option.design_checkbox_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignCheckboxOptionId(String designCheckboxOptionId) {
        this.designCheckboxOptionId = designCheckboxOptionId == null ? null : designCheckboxOptionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_checkbox_option.design_checkbox_id
     *
     * @return the value of design_checkbox_option.design_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDesignCheckboxId() {
        return designCheckboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_checkbox_option.design_checkbox_id
     *
     * @param designCheckboxId the value for design_checkbox_option.design_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignCheckboxId(String designCheckboxId) {
        this.designCheckboxId = designCheckboxId == null ? null : designCheckboxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_checkbox_option.design_checkbox_order
     *
     * @return the value of design_checkbox_option.design_checkbox_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Integer getDesignCheckboxOrder() {
        return designCheckboxOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_checkbox_option.design_checkbox_order
     *
     * @param designCheckboxOrder the value for design_checkbox_option.design_checkbox_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignCheckboxOrder(Integer designCheckboxOrder) {
        this.designCheckboxOrder = designCheckboxOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_checkbox_option.design_checkbox_option_content
     *
     * @return the value of design_checkbox_option.design_checkbox_option_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDesignCheckboxOptionContent() {
        return designCheckboxOptionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_checkbox_option.design_checkbox_option_content
     *
     * @param designCheckboxOptionContent the value for design_checkbox_option.design_checkbox_option_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignCheckboxOptionContent(String designCheckboxOptionContent) {
        this.designCheckboxOptionContent = designCheckboxOptionContent == null ? null : designCheckboxOptionContent.trim();
    }
}