package com.vo;

public class DesignCheckbox {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_checkbox.design_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String designCheckboxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_checkbox.design_checkbox_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String designCheckboxContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_checkbox.design_checkbox_id
     *
     * @return the value of design_checkbox.design_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDesignCheckboxId() {
        return designCheckboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_checkbox.design_checkbox_id
     *
     * @param designCheckboxId the value for design_checkbox.design_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignCheckboxId(String designCheckboxId) {
        this.designCheckboxId = designCheckboxId == null ? null : designCheckboxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_checkbox.design_checkbox_content
     *
     * @return the value of design_checkbox.design_checkbox_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDesignCheckboxContent() {
        return designCheckboxContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_checkbox.design_checkbox_content
     *
     * @param designCheckboxContent the value for design_checkbox.design_checkbox_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignCheckboxContent(String designCheckboxContent) {
        this.designCheckboxContent = designCheckboxContent == null ? null : designCheckboxContent.trim();
    }
}