package com.vo;

import java.util.ArrayList;
import java.util.List;

public class DesignTempletIndexExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public DesignTempletIndexExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDesignTempletIndexIdIsNull() {
            addCriterion("design_templet_index_id is null");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdIsNotNull() {
            addCriterion("design_templet_index_id is not null");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdEqualTo(String value) {
            addCriterion("design_templet_index_id =", value, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdNotEqualTo(String value) {
            addCriterion("design_templet_index_id <>", value, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdGreaterThan(String value) {
            addCriterion("design_templet_index_id >", value, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdGreaterThanOrEqualTo(String value) {
            addCriterion("design_templet_index_id >=", value, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdLessThan(String value) {
            addCriterion("design_templet_index_id <", value, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdLessThanOrEqualTo(String value) {
            addCriterion("design_templet_index_id <=", value, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdLike(String value) {
            addCriterion("design_templet_index_id like", value, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdNotLike(String value) {
            addCriterion("design_templet_index_id not like", value, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdIn(List<String> values) {
            addCriterion("design_templet_index_id in", values, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdNotIn(List<String> values) {
            addCriterion("design_templet_index_id not in", values, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdBetween(String value1, String value2) {
            addCriterion("design_templet_index_id between", value1, value2, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexIdNotBetween(String value1, String value2) {
            addCriterion("design_templet_index_id not between", value1, value2, "designTempletIndexId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignIsNull() {
            addCriterion("design_templet_index_sign is null");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignIsNotNull() {
            addCriterion("design_templet_index_sign is not null");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignEqualTo(Integer value) {
            addCriterion("design_templet_index_sign =", value, "designTempletIndexSign");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignNotEqualTo(Integer value) {
            addCriterion("design_templet_index_sign <>", value, "designTempletIndexSign");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignGreaterThan(Integer value) {
            addCriterion("design_templet_index_sign >", value, "designTempletIndexSign");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignGreaterThanOrEqualTo(Integer value) {
            addCriterion("design_templet_index_sign >=", value, "designTempletIndexSign");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignLessThan(Integer value) {
            addCriterion("design_templet_index_sign <", value, "designTempletIndexSign");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignLessThanOrEqualTo(Integer value) {
            addCriterion("design_templet_index_sign <=", value, "designTempletIndexSign");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignIn(List<Integer> values) {
            addCriterion("design_templet_index_sign in", values, "designTempletIndexSign");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignNotIn(List<Integer> values) {
            addCriterion("design_templet_index_sign not in", values, "designTempletIndexSign");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignBetween(Integer value1, Integer value2) {
            addCriterion("design_templet_index_sign between", value1, value2, "designTempletIndexSign");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexSignNotBetween(Integer value1, Integer value2) {
            addCriterion("design_templet_index_sign not between", value1, value2, "designTempletIndexSign");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderIsNull() {
            addCriterion("design_templet_index_order is null");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderIsNotNull() {
            addCriterion("design_templet_index_order is not null");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderEqualTo(Integer value) {
            addCriterion("design_templet_index_order =", value, "designTempletIndexOrder");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderNotEqualTo(Integer value) {
            addCriterion("design_templet_index_order <>", value, "designTempletIndexOrder");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderGreaterThan(Integer value) {
            addCriterion("design_templet_index_order >", value, "designTempletIndexOrder");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("design_templet_index_order >=", value, "designTempletIndexOrder");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderLessThan(Integer value) {
            addCriterion("design_templet_index_order <", value, "designTempletIndexOrder");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderLessThanOrEqualTo(Integer value) {
            addCriterion("design_templet_index_order <=", value, "designTempletIndexOrder");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderIn(List<Integer> values) {
            addCriterion("design_templet_index_order in", values, "designTempletIndexOrder");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderNotIn(List<Integer> values) {
            addCriterion("design_templet_index_order not in", values, "designTempletIndexOrder");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderBetween(Integer value1, Integer value2) {
            addCriterion("design_templet_index_order between", value1, value2, "designTempletIndexOrder");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIndexOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("design_templet_index_order not between", value1, value2, "designTempletIndexOrder");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdIsNull() {
            addCriterion("design_exercise_id is null");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdIsNotNull() {
            addCriterion("design_exercise_id is not null");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdEqualTo(String value) {
            addCriterion("design_exercise_id =", value, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdNotEqualTo(String value) {
            addCriterion("design_exercise_id <>", value, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdGreaterThan(String value) {
            addCriterion("design_exercise_id >", value, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdGreaterThanOrEqualTo(String value) {
            addCriterion("design_exercise_id >=", value, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdLessThan(String value) {
            addCriterion("design_exercise_id <", value, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdLessThanOrEqualTo(String value) {
            addCriterion("design_exercise_id <=", value, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdLike(String value) {
            addCriterion("design_exercise_id like", value, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdNotLike(String value) {
            addCriterion("design_exercise_id not like", value, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdIn(List<String> values) {
            addCriterion("design_exercise_id in", values, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdNotIn(List<String> values) {
            addCriterion("design_exercise_id not in", values, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdBetween(String value1, String value2) {
            addCriterion("design_exercise_id between", value1, value2, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignExerciseIdNotBetween(String value1, String value2) {
            addCriterion("design_exercise_id not between", value1, value2, "designExerciseId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdIsNull() {
            addCriterion("design_templet_id is null");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdIsNotNull() {
            addCriterion("design_templet_id is not null");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdEqualTo(String value) {
            addCriterion("design_templet_id =", value, "designTempletId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdNotEqualTo(String value) {
            addCriterion("design_templet_id <>", value, "designTempletId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdGreaterThan(String value) {
            addCriterion("design_templet_id >", value, "designTempletId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdGreaterThanOrEqualTo(String value) {
            addCriterion("design_templet_id >=", value, "designTempletId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdLessThan(String value) {
            addCriterion("design_templet_id <", value, "designTempletId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdLessThanOrEqualTo(String value) {
            addCriterion("design_templet_id <=", value, "designTempletId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdLike(String value) {
            addCriterion("design_templet_id like", value, "designTempletId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdNotLike(String value) {
            addCriterion("design_templet_id not like", value, "designTempletId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdIn(List<String> values) {
            addCriterion("design_templet_id in", values, "designTempletId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdNotIn(List<String> values) {
            addCriterion("design_templet_id not in", values, "designTempletId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdBetween(String value1, String value2) {
            addCriterion("design_templet_id between", value1, value2, "designTempletId");
            return (Criteria) this;
        }

        public Criteria andDesignTempletIdNotBetween(String value1, String value2) {
            addCriterion("design_templet_id not between", value1, value2, "designTempletId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table design_templet_index
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 12 09:03:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table design_templet_index
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}