package com.vo;

import java.util.Date;

public class DesignTemplet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_templet.design_templet_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String designTempletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_templet.design_templet_name
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String designTempletName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_templet.finish_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_templet.start_recovery_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Date startRecoveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_templet.end_recovery_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Date endRecoveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_templet.state
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_templet.link
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column design_templet.user_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_templet.design_templet_id
     *
     * @return the value of design_templet.design_templet_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDesignTempletId() {
        return designTempletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_templet.design_templet_id
     *
     * @param designTempletId the value for design_templet.design_templet_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignTempletId(String designTempletId) {
        this.designTempletId = designTempletId == null ? null : designTempletId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_templet.design_templet_name
     *
     * @return the value of design_templet.design_templet_name
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDesignTempletName() {
        return designTempletName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_templet.design_templet_name
     *
     * @param designTempletName the value for design_templet.design_templet_name
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignTempletName(String designTempletName) {
        this.designTempletName = designTempletName == null ? null : designTempletName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_templet.finish_time
     *
     * @return the value of design_templet.finish_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_templet.finish_time
     *
     * @param finishTime the value for design_templet.finish_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_templet.start_recovery_time
     *
     * @return the value of design_templet.start_recovery_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Date getStartRecoveryTime() {
        return startRecoveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_templet.start_recovery_time
     *
     * @param startRecoveryTime the value for design_templet.start_recovery_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setStartRecoveryTime(Date startRecoveryTime) {
        this.startRecoveryTime = startRecoveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_templet.end_recovery_time
     *
     * @return the value of design_templet.end_recovery_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Date getEndRecoveryTime() {
        return endRecoveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_templet.end_recovery_time
     *
     * @param endRecoveryTime the value for design_templet.end_recovery_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setEndRecoveryTime(Date endRecoveryTime) {
        this.endRecoveryTime = endRecoveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_templet.state
     *
     * @return the value of design_templet.state
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_templet.state
     *
     * @param state the value for design_templet.state
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_templet.link
     *
     * @return the value of design_templet.link
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_templet.link
     *
     * @param link the value for design_templet.link
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column design_templet.user_id
     *
     * @return the value of design_templet.user_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column design_templet.user_id
     *
     * @param userId the value for design_templet.user_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}