package com.vo;

public class DictTempletIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_templet_index.dict_templet_index_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictTempletIndexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_templet_index.dict_templet_index_sign
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Integer dictTempletIndexSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_templet_index.dict_templet_index_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Integer dictTempletIndexOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_templet_index.dict_exercise_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictExerciseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_templet_index.dict_templet_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictTempletId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_templet_index.dict_templet_index_id
     *
     * @return the value of dict_templet_index.dict_templet_index_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictTempletIndexId() {
        return dictTempletIndexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_templet_index.dict_templet_index_id
     *
     * @param dictTempletIndexId the value for dict_templet_index.dict_templet_index_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictTempletIndexId(String dictTempletIndexId) {
        this.dictTempletIndexId = dictTempletIndexId == null ? null : dictTempletIndexId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_templet_index.dict_templet_index_sign
     *
     * @return the value of dict_templet_index.dict_templet_index_sign
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Integer getDictTempletIndexSign() {
        return dictTempletIndexSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_templet_index.dict_templet_index_sign
     *
     * @param dictTempletIndexSign the value for dict_templet_index.dict_templet_index_sign
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictTempletIndexSign(Integer dictTempletIndexSign) {
        this.dictTempletIndexSign = dictTempletIndexSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_templet_index.dict_templet_index_order
     *
     * @return the value of dict_templet_index.dict_templet_index_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Integer getDictTempletIndexOrder() {
        return dictTempletIndexOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_templet_index.dict_templet_index_order
     *
     * @param dictTempletIndexOrder the value for dict_templet_index.dict_templet_index_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictTempletIndexOrder(Integer dictTempletIndexOrder) {
        this.dictTempletIndexOrder = dictTempletIndexOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_templet_index.dict_exercise_id
     *
     * @return the value of dict_templet_index.dict_exercise_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictExerciseId() {
        return dictExerciseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_templet_index.dict_exercise_id
     *
     * @param dictExerciseId the value for dict_templet_index.dict_exercise_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictExerciseId(String dictExerciseId) {
        this.dictExerciseId = dictExerciseId == null ? null : dictExerciseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_templet_index.dict_templet_id
     *
     * @return the value of dict_templet_index.dict_templet_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictTempletId() {
        return dictTempletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_templet_index.dict_templet_id
     *
     * @param dictTempletId the value for dict_templet_index.dict_templet_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictTempletId(String dictTempletId) {
        this.dictTempletId = dictTempletId == null ? null : dictTempletId.trim();
    }
}