package com.vo;

public class DictTemplet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_templet.dict_templet_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictTempletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_templet.dict_templet_name
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictTempletName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_templet.sort_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String sortId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_templet.dict_templet_id
     *
     * @return the value of dict_templet.dict_templet_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictTempletId() {
        return dictTempletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_templet.dict_templet_id
     *
     * @param dictTempletId the value for dict_templet.dict_templet_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictTempletId(String dictTempletId) {
        this.dictTempletId = dictTempletId == null ? null : dictTempletId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_templet.dict_templet_name
     *
     * @return the value of dict_templet.dict_templet_name
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictTempletName() {
        return dictTempletName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_templet.dict_templet_name
     *
     * @param dictTempletName the value for dict_templet.dict_templet_name
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictTempletName(String dictTempletName) {
        this.dictTempletName = dictTempletName == null ? null : dictTempletName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_templet.sort_id
     *
     * @return the value of dict_templet.sort_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_templet.sort_id
     *
     * @param sortId the value for dict_templet.sort_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setSortId(String sortId) {
        this.sortId = sortId == null ? null : sortId.trim();
    }
}