package com.vo;

public class DictCheckboxOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_checkbox_option.dict_checkbox_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictCheckboxOptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_checkbox_option.dict_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictCheckboxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_checkbox_option.dict_checkbox_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Integer dictCheckboxOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_checkbox_option.dict_checkbox_option_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictCheckboxOptionContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_checkbox_option.dict_checkbox_option_id
     *
     * @return the value of dict_checkbox_option.dict_checkbox_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictCheckboxOptionId() {
        return dictCheckboxOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_checkbox_option.dict_checkbox_option_id
     *
     * @param dictCheckboxOptionId the value for dict_checkbox_option.dict_checkbox_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictCheckboxOptionId(String dictCheckboxOptionId) {
        this.dictCheckboxOptionId = dictCheckboxOptionId == null ? null : dictCheckboxOptionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_checkbox_option.dict_checkbox_id
     *
     * @return the value of dict_checkbox_option.dict_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictCheckboxId() {
        return dictCheckboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_checkbox_option.dict_checkbox_id
     *
     * @param dictCheckboxId the value for dict_checkbox_option.dict_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictCheckboxId(String dictCheckboxId) {
        this.dictCheckboxId = dictCheckboxId == null ? null : dictCheckboxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_checkbox_option.dict_checkbox_order
     *
     * @return the value of dict_checkbox_option.dict_checkbox_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Integer getDictCheckboxOrder() {
        return dictCheckboxOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_checkbox_option.dict_checkbox_order
     *
     * @param dictCheckboxOrder the value for dict_checkbox_option.dict_checkbox_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictCheckboxOrder(Integer dictCheckboxOrder) {
        this.dictCheckboxOrder = dictCheckboxOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_checkbox_option.dict_checkbox_option_content
     *
     * @return the value of dict_checkbox_option.dict_checkbox_option_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictCheckboxOptionContent() {
        return dictCheckboxOptionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_checkbox_option.dict_checkbox_option_content
     *
     * @param dictCheckboxOptionContent the value for dict_checkbox_option.dict_checkbox_option_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictCheckboxOptionContent(String dictCheckboxOptionContent) {
        this.dictCheckboxOptionContent = dictCheckboxOptionContent == null ? null : dictCheckboxOptionContent.trim();
    }
}