package com.vo;

import java.util.ArrayList;
import java.util.List;

public class DictCheckboxOptionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public DictCheckboxOptionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDictCheckboxOptionIdIsNull() {
            addCriterion("dict_checkbox_option_id is null");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdIsNotNull() {
            addCriterion("dict_checkbox_option_id is not null");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdEqualTo(String value) {
            addCriterion("dict_checkbox_option_id =", value, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdNotEqualTo(String value) {
            addCriterion("dict_checkbox_option_id <>", value, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdGreaterThan(String value) {
            addCriterion("dict_checkbox_option_id >", value, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdGreaterThanOrEqualTo(String value) {
            addCriterion("dict_checkbox_option_id >=", value, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdLessThan(String value) {
            addCriterion("dict_checkbox_option_id <", value, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdLessThanOrEqualTo(String value) {
            addCriterion("dict_checkbox_option_id <=", value, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdLike(String value) {
            addCriterion("dict_checkbox_option_id like", value, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdNotLike(String value) {
            addCriterion("dict_checkbox_option_id not like", value, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdIn(List<String> values) {
            addCriterion("dict_checkbox_option_id in", values, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdNotIn(List<String> values) {
            addCriterion("dict_checkbox_option_id not in", values, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdBetween(String value1, String value2) {
            addCriterion("dict_checkbox_option_id between", value1, value2, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionIdNotBetween(String value1, String value2) {
            addCriterion("dict_checkbox_option_id not between", value1, value2, "dictCheckboxOptionId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdIsNull() {
            addCriterion("dict_checkbox_id is null");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdIsNotNull() {
            addCriterion("dict_checkbox_id is not null");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdEqualTo(String value) {
            addCriterion("dict_checkbox_id =", value, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdNotEqualTo(String value) {
            addCriterion("dict_checkbox_id <>", value, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdGreaterThan(String value) {
            addCriterion("dict_checkbox_id >", value, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdGreaterThanOrEqualTo(String value) {
            addCriterion("dict_checkbox_id >=", value, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdLessThan(String value) {
            addCriterion("dict_checkbox_id <", value, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdLessThanOrEqualTo(String value) {
            addCriterion("dict_checkbox_id <=", value, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdLike(String value) {
            addCriterion("dict_checkbox_id like", value, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdNotLike(String value) {
            addCriterion("dict_checkbox_id not like", value, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdIn(List<String> values) {
            addCriterion("dict_checkbox_id in", values, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdNotIn(List<String> values) {
            addCriterion("dict_checkbox_id not in", values, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdBetween(String value1, String value2) {
            addCriterion("dict_checkbox_id between", value1, value2, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxIdNotBetween(String value1, String value2) {
            addCriterion("dict_checkbox_id not between", value1, value2, "dictCheckboxId");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderIsNull() {
            addCriterion("dict_checkbox_order is null");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderIsNotNull() {
            addCriterion("dict_checkbox_order is not null");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderEqualTo(Integer value) {
            addCriterion("dict_checkbox_order =", value, "dictCheckboxOrder");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderNotEqualTo(Integer value) {
            addCriterion("dict_checkbox_order <>", value, "dictCheckboxOrder");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderGreaterThan(Integer value) {
            addCriterion("dict_checkbox_order >", value, "dictCheckboxOrder");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("dict_checkbox_order >=", value, "dictCheckboxOrder");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderLessThan(Integer value) {
            addCriterion("dict_checkbox_order <", value, "dictCheckboxOrder");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderLessThanOrEqualTo(Integer value) {
            addCriterion("dict_checkbox_order <=", value, "dictCheckboxOrder");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderIn(List<Integer> values) {
            addCriterion("dict_checkbox_order in", values, "dictCheckboxOrder");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderNotIn(List<Integer> values) {
            addCriterion("dict_checkbox_order not in", values, "dictCheckboxOrder");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderBetween(Integer value1, Integer value2) {
            addCriterion("dict_checkbox_order between", value1, value2, "dictCheckboxOrder");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("dict_checkbox_order not between", value1, value2, "dictCheckboxOrder");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentIsNull() {
            addCriterion("dict_checkbox_option_content is null");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentIsNotNull() {
            addCriterion("dict_checkbox_option_content is not null");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentEqualTo(String value) {
            addCriterion("dict_checkbox_option_content =", value, "dictCheckboxOptionContent");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentNotEqualTo(String value) {
            addCriterion("dict_checkbox_option_content <>", value, "dictCheckboxOptionContent");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentGreaterThan(String value) {
            addCriterion("dict_checkbox_option_content >", value, "dictCheckboxOptionContent");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentGreaterThanOrEqualTo(String value) {
            addCriterion("dict_checkbox_option_content >=", value, "dictCheckboxOptionContent");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentLessThan(String value) {
            addCriterion("dict_checkbox_option_content <", value, "dictCheckboxOptionContent");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentLessThanOrEqualTo(String value) {
            addCriterion("dict_checkbox_option_content <=", value, "dictCheckboxOptionContent");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentLike(String value) {
            addCriterion("dict_checkbox_option_content like", value, "dictCheckboxOptionContent");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentNotLike(String value) {
            addCriterion("dict_checkbox_option_content not like", value, "dictCheckboxOptionContent");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentIn(List<String> values) {
            addCriterion("dict_checkbox_option_content in", values, "dictCheckboxOptionContent");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentNotIn(List<String> values) {
            addCriterion("dict_checkbox_option_content not in", values, "dictCheckboxOptionContent");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentBetween(String value1, String value2) {
            addCriterion("dict_checkbox_option_content between", value1, value2, "dictCheckboxOptionContent");
            return (Criteria) this;
        }

        public Criteria andDictCheckboxOptionContentNotBetween(String value1, String value2) {
            addCriterion("dict_checkbox_option_content not between", value1, value2, "dictCheckboxOptionContent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 12 09:03:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dict_checkbox_option
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}