package com.vo;

public class DictSingleOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_single_option.dict_single_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictSingleOptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_single_option.dict_single_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictSingleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_single_option.dict_single_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Integer dictSingleOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_single_option.dict_single_option_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictSingleOptionContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_single_option.dict_single_option_id
     *
     * @return the value of dict_single_option.dict_single_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictSingleOptionId() {
        return dictSingleOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_single_option.dict_single_option_id
     *
     * @param dictSingleOptionId the value for dict_single_option.dict_single_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictSingleOptionId(String dictSingleOptionId) {
        this.dictSingleOptionId = dictSingleOptionId == null ? null : dictSingleOptionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_single_option.dict_single_id
     *
     * @return the value of dict_single_option.dict_single_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictSingleId() {
        return dictSingleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_single_option.dict_single_id
     *
     * @param dictSingleId the value for dict_single_option.dict_single_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictSingleId(String dictSingleId) {
        this.dictSingleId = dictSingleId == null ? null : dictSingleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_single_option.dict_single_order
     *
     * @return the value of dict_single_option.dict_single_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Integer getDictSingleOrder() {
        return dictSingleOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_single_option.dict_single_order
     *
     * @param dictSingleOrder the value for dict_single_option.dict_single_order
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictSingleOrder(Integer dictSingleOrder) {
        this.dictSingleOrder = dictSingleOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_single_option.dict_single_option_content
     *
     * @return the value of dict_single_option.dict_single_option_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictSingleOptionContent() {
        return dictSingleOptionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_single_option.dict_single_option_content
     *
     * @param dictSingleOptionContent the value for dict_single_option.dict_single_option_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictSingleOptionContent(String dictSingleOptionContent) {
        this.dictSingleOptionContent = dictSingleOptionContent == null ? null : dictSingleOptionContent.trim();
    }
}