package com.vo;

public class DictCheckbox {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_checkbox.dict_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictCheckboxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_checkbox.dict_checkbox_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String dictCheckboxContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_checkbox.dict_checkbox_id
     *
     * @return the value of dict_checkbox.dict_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictCheckboxId() {
        return dictCheckboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_checkbox.dict_checkbox_id
     *
     * @param dictCheckboxId the value for dict_checkbox.dict_checkbox_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictCheckboxId(String dictCheckboxId) {
        this.dictCheckboxId = dictCheckboxId == null ? null : dictCheckboxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_checkbox.dict_checkbox_content
     *
     * @return the value of dict_checkbox.dict_checkbox_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDictCheckboxContent() {
        return dictCheckboxContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_checkbox.dict_checkbox_content
     *
     * @param dictCheckboxContent the value for dict_checkbox.dict_checkbox_content
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDictCheckboxContent(String dictCheckboxContent) {
        this.dictCheckboxContent = dictCheckboxContent == null ? null : dictCheckboxContent.trim();
    }
}