package com.vo;

public class SingleAnswerCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column single_answer_count.single_answer_count_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String singleAnswerCountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column single_answer_count.single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Integer singleAnswerCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column single_answer_count.design_single_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String designSingleOptionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column single_answer_count.single_answer_count_id
     *
     * @return the value of single_answer_count.single_answer_count_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getSingleAnswerCountId() {
        return singleAnswerCountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column single_answer_count.single_answer_count_id
     *
     * @param singleAnswerCountId the value for single_answer_count.single_answer_count_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setSingleAnswerCountId(String singleAnswerCountId) {
        this.singleAnswerCountId = singleAnswerCountId == null ? null : singleAnswerCountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column single_answer_count.single_answer_count
     *
     * @return the value of single_answer_count.single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Integer getSingleAnswerCount() {
        return singleAnswerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column single_answer_count.single_answer_count
     *
     * @param singleAnswerCount the value for single_answer_count.single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setSingleAnswerCount(Integer singleAnswerCount) {
        this.singleAnswerCount = singleAnswerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column single_answer_count.design_single_option_id
     *
     * @return the value of single_answer_count.design_single_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getDesignSingleOptionId() {
        return designSingleOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column single_answer_count.design_single_option_id
     *
     * @param designSingleOptionId the value for single_answer_count.design_single_option_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDesignSingleOptionId(String designSingleOptionId) {
        this.designSingleOptionId = designSingleOptionId == null ? null : designSingleOptionId.trim();
    }
}