package com.vo;

import java.util.ArrayList;
import java.util.List;

public class SingleAnswerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    public SingleAnswerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSingleAnswerIdIsNull() {
            addCriterion("single_answer_id is null");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdIsNotNull() {
            addCriterion("single_answer_id is not null");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdEqualTo(String value) {
            addCriterion("single_answer_id =", value, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdNotEqualTo(String value) {
            addCriterion("single_answer_id <>", value, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdGreaterThan(String value) {
            addCriterion("single_answer_id >", value, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdGreaterThanOrEqualTo(String value) {
            addCriterion("single_answer_id >=", value, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdLessThan(String value) {
            addCriterion("single_answer_id <", value, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdLessThanOrEqualTo(String value) {
            addCriterion("single_answer_id <=", value, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdLike(String value) {
            addCriterion("single_answer_id like", value, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdNotLike(String value) {
            addCriterion("single_answer_id not like", value, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdIn(List<String> values) {
            addCriterion("single_answer_id in", values, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdNotIn(List<String> values) {
            addCriterion("single_answer_id not in", values, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdBetween(String value1, String value2) {
            addCriterion("single_answer_id between", value1, value2, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIdNotBetween(String value1, String value2) {
            addCriterion("single_answer_id not between", value1, value2, "singleAnswerId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdIsNull() {
            addCriterion("design_single_id is null");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdIsNotNull() {
            addCriterion("design_single_id is not null");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdEqualTo(String value) {
            addCriterion("design_single_id =", value, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdNotEqualTo(String value) {
            addCriterion("design_single_id <>", value, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdGreaterThan(String value) {
            addCriterion("design_single_id >", value, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdGreaterThanOrEqualTo(String value) {
            addCriterion("design_single_id >=", value, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdLessThan(String value) {
            addCriterion("design_single_id <", value, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdLessThanOrEqualTo(String value) {
            addCriterion("design_single_id <=", value, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdLike(String value) {
            addCriterion("design_single_id like", value, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdNotLike(String value) {
            addCriterion("design_single_id not like", value, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdIn(List<String> values) {
            addCriterion("design_single_id in", values, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdNotIn(List<String> values) {
            addCriterion("design_single_id not in", values, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdBetween(String value1, String value2) {
            addCriterion("design_single_id between", value1, value2, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleIdNotBetween(String value1, String value2) {
            addCriterion("design_single_id not between", value1, value2, "designSingleId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdIsNull() {
            addCriterion("dict_single_option_id is null");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdIsNotNull() {
            addCriterion("dict_single_option_id is not null");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdEqualTo(String value) {
            addCriterion("dict_single_option_id =", value, "dictSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdNotEqualTo(String value) {
            addCriterion("dict_single_option_id <>", value, "dictSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdGreaterThan(String value) {
            addCriterion("dict_single_option_id >", value, "dictSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdGreaterThanOrEqualTo(String value) {
            addCriterion("dict_single_option_id >=", value, "dictSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdLessThan(String value) {
            addCriterion("dict_single_option_id <", value, "dictSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdLessThanOrEqualTo(String value) {
            addCriterion("dict_single_option_id <=", value, "dictSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdLike(String value) {
            addCriterion("dict_single_option_id like", value, "dictSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdNotLike(String value) {
            addCriterion("dict_single_option_id not like", value, "dictSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdIn(List<String> values) {
            addCriterion("dict_single_option_id in", values, "dictSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdNotIn(List<String> values) {
            addCriterion("dict_single_option_id not in", values, "dictSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdBetween(String value1, String value2) {
            addCriterion("dict_single_option_id between", value1, value2, "dictSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDictSingleOptionIdNotBetween(String value1, String value2) {
            addCriterion("dict_single_option_id not between", value1, value2, "dictSingleOptionId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table single_answer
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 07 16:26:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table single_answer
     *
     * @mbggenerated Sun Jan 07 16:26:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}