package com.vo;

import java.util.ArrayList;
import java.util.List;

public class SingleAnswerCountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public SingleAnswerCountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSingleAnswerCountIdIsNull() {
            addCriterion("single_answer_count_id is null");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdIsNotNull() {
            addCriterion("single_answer_count_id is not null");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdEqualTo(String value) {
            addCriterion("single_answer_count_id =", value, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdNotEqualTo(String value) {
            addCriterion("single_answer_count_id <>", value, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdGreaterThan(String value) {
            addCriterion("single_answer_count_id >", value, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdGreaterThanOrEqualTo(String value) {
            addCriterion("single_answer_count_id >=", value, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdLessThan(String value) {
            addCriterion("single_answer_count_id <", value, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdLessThanOrEqualTo(String value) {
            addCriterion("single_answer_count_id <=", value, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdLike(String value) {
            addCriterion("single_answer_count_id like", value, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdNotLike(String value) {
            addCriterion("single_answer_count_id not like", value, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdIn(List<String> values) {
            addCriterion("single_answer_count_id in", values, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdNotIn(List<String> values) {
            addCriterion("single_answer_count_id not in", values, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdBetween(String value1, String value2) {
            addCriterion("single_answer_count_id between", value1, value2, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIdNotBetween(String value1, String value2) {
            addCriterion("single_answer_count_id not between", value1, value2, "singleAnswerCountId");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIsNull() {
            addCriterion("single_answer_count is null");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIsNotNull() {
            addCriterion("single_answer_count is not null");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountEqualTo(Integer value) {
            addCriterion("single_answer_count =", value, "singleAnswerCount");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountNotEqualTo(Integer value) {
            addCriterion("single_answer_count <>", value, "singleAnswerCount");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountGreaterThan(Integer value) {
            addCriterion("single_answer_count >", value, "singleAnswerCount");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("single_answer_count >=", value, "singleAnswerCount");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountLessThan(Integer value) {
            addCriterion("single_answer_count <", value, "singleAnswerCount");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountLessThanOrEqualTo(Integer value) {
            addCriterion("single_answer_count <=", value, "singleAnswerCount");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountIn(List<Integer> values) {
            addCriterion("single_answer_count in", values, "singleAnswerCount");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountNotIn(List<Integer> values) {
            addCriterion("single_answer_count not in", values, "singleAnswerCount");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountBetween(Integer value1, Integer value2) {
            addCriterion("single_answer_count between", value1, value2, "singleAnswerCount");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerCountNotBetween(Integer value1, Integer value2) {
            addCriterion("single_answer_count not between", value1, value2, "singleAnswerCount");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdIsNull() {
            addCriterion("design_single_option_id is null");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdIsNotNull() {
            addCriterion("design_single_option_id is not null");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdEqualTo(String value) {
            addCriterion("design_single_option_id =", value, "designSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdNotEqualTo(String value) {
            addCriterion("design_single_option_id <>", value, "designSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdGreaterThan(String value) {
            addCriterion("design_single_option_id >", value, "designSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdGreaterThanOrEqualTo(String value) {
            addCriterion("design_single_option_id >=", value, "designSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdLessThan(String value) {
            addCriterion("design_single_option_id <", value, "designSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdLessThanOrEqualTo(String value) {
            addCriterion("design_single_option_id <=", value, "designSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdLike(String value) {
            addCriterion("design_single_option_id like", value, "designSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdNotLike(String value) {
            addCriterion("design_single_option_id not like", value, "designSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdIn(List<String> values) {
            addCriterion("design_single_option_id in", values, "designSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdNotIn(List<String> values) {
            addCriterion("design_single_option_id not in", values, "designSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdBetween(String value1, String value2) {
            addCriterion("design_single_option_id between", value1, value2, "designSingleOptionId");
            return (Criteria) this;
        }

        public Criteria andDesignSingleOptionIdNotBetween(String value1, String value2) {
            addCriterion("design_single_option_id not between", value1, value2, "designSingleOptionId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table single_answer_count
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 12 09:03:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table single_answer_count
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}