package com.vo;

public class UserOperateProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_project.user_operate_project_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String userOperateProjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_project.user_operate_project_show
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String userOperateProjectShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_project.user_operate_project_id
     *
     * @return the value of user_operate_project.user_operate_project_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getUserOperateProjectId() {
        return userOperateProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_project.user_operate_project_id
     *
     * @param userOperateProjectId the value for user_operate_project.user_operate_project_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setUserOperateProjectId(String userOperateProjectId) {
        this.userOperateProjectId = userOperateProjectId == null ? null : userOperateProjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_project.user_operate_project_show
     *
     * @return the value of user_operate_project.user_operate_project_show
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getUserOperateProjectShow() {
        return userOperateProjectShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_project.user_operate_project_show
     *
     * @param userOperateProjectShow the value for user_operate_project.user_operate_project_show
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setUserOperateProjectShow(String userOperateProjectShow) {
        this.userOperateProjectShow = userOperateProjectShow == null ? null : userOperateProjectShow.trim();
    }
}