package com.vo;

import java.util.Date;

public class UserLoginLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.user_login_log_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String userLoginLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.user_login_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private Date userLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.user_login_account
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String userLoginAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.user_login_result_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    private String userLoginResultId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.user_login_log_id
     *
     * @return the value of user_login_log.user_login_log_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getUserLoginLogId() {
        return userLoginLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.user_login_log_id
     *
     * @param userLoginLogId the value for user_login_log.user_login_log_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setUserLoginLogId(String userLoginLogId) {
        this.userLoginLogId = userLoginLogId == null ? null : userLoginLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.user_login_time
     *
     * @return the value of user_login_log.user_login_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Date getUserLoginTime() {
        return userLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.user_login_time
     *
     * @param userLoginTime the value for user_login_log.user_login_time
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setUserLoginTime(Date userLoginTime) {
        this.userLoginTime = userLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.user_login_account
     *
     * @return the value of user_login_log.user_login_account
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getUserLoginAccount() {
        return userLoginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.user_login_account
     *
     * @param userLoginAccount the value for user_login_log.user_login_account
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setUserLoginAccount(String userLoginAccount) {
        this.userLoginAccount = userLoginAccount == null ? null : userLoginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.user_login_result_id
     *
     * @return the value of user_login_log.user_login_result_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getUserLoginResultId() {
        return userLoginResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.user_login_result_id
     *
     * @param userLoginResultId the value for user_login_log.user_login_result_id
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setUserLoginResultId(String userLoginResultId) {
        this.userLoginResultId = userLoginResultId == null ? null : userLoginResultId.trim();
    }
}