package com.vo;

public class UserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Sat Jan 06 16:52:27 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.design_templet_id
     *
     * @mbggenerated Sat Jan 06 16:52:27 CST 2018
     */
    private String designTempletId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Sat Jan 06 16:52:27 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Sat Jan 06 16:52:27 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.design_templet_id
     *
     * @return the value of user.design_templet_id
     *
     * @mbggenerated Sat Jan 06 16:52:27 CST 2018
     */
    public String getDesignTempletId() {
        return designTempletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.design_templet_id
     *
     * @param designTempletId the value for user.design_templet_id
     *
     * @mbggenerated Sat Jan 06 16:52:27 CST 2018
     */
    public void setDesignTempletId(String designTempletId) {
        this.designTempletId = designTempletId == null ? null : designTempletId.trim();
    }
}