package com.vo;

import java.util.ArrayList;
import java.util.List;

public class UserOperateProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public UserOperateProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserOperateProjectIdIsNull() {
            addCriterion("user_operate_project_id is null");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdIsNotNull() {
            addCriterion("user_operate_project_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdEqualTo(String value) {
            addCriterion("user_operate_project_id =", value, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdNotEqualTo(String value) {
            addCriterion("user_operate_project_id <>", value, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdGreaterThan(String value) {
            addCriterion("user_operate_project_id >", value, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_operate_project_id >=", value, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdLessThan(String value) {
            addCriterion("user_operate_project_id <", value, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdLessThanOrEqualTo(String value) {
            addCriterion("user_operate_project_id <=", value, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdLike(String value) {
            addCriterion("user_operate_project_id like", value, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdNotLike(String value) {
            addCriterion("user_operate_project_id not like", value, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdIn(List<String> values) {
            addCriterion("user_operate_project_id in", values, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdNotIn(List<String> values) {
            addCriterion("user_operate_project_id not in", values, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdBetween(String value1, String value2) {
            addCriterion("user_operate_project_id between", value1, value2, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectIdNotBetween(String value1, String value2) {
            addCriterion("user_operate_project_id not between", value1, value2, "userOperateProjectId");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowIsNull() {
            addCriterion("user_operate_project_show is null");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowIsNotNull() {
            addCriterion("user_operate_project_show is not null");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowEqualTo(String value) {
            addCriterion("user_operate_project_show =", value, "userOperateProjectShow");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowNotEqualTo(String value) {
            addCriterion("user_operate_project_show <>", value, "userOperateProjectShow");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowGreaterThan(String value) {
            addCriterion("user_operate_project_show >", value, "userOperateProjectShow");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowGreaterThanOrEqualTo(String value) {
            addCriterion("user_operate_project_show >=", value, "userOperateProjectShow");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowLessThan(String value) {
            addCriterion("user_operate_project_show <", value, "userOperateProjectShow");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowLessThanOrEqualTo(String value) {
            addCriterion("user_operate_project_show <=", value, "userOperateProjectShow");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowLike(String value) {
            addCriterion("user_operate_project_show like", value, "userOperateProjectShow");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowNotLike(String value) {
            addCriterion("user_operate_project_show not like", value, "userOperateProjectShow");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowIn(List<String> values) {
            addCriterion("user_operate_project_show in", values, "userOperateProjectShow");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowNotIn(List<String> values) {
            addCriterion("user_operate_project_show not in", values, "userOperateProjectShow");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowBetween(String value1, String value2) {
            addCriterion("user_operate_project_show between", value1, value2, "userOperateProjectShow");
            return (Criteria) this;
        }

        public Criteria andUserOperateProjectShowNotBetween(String value1, String value2) {
            addCriterion("user_operate_project_show not between", value1, value2, "userOperateProjectShow");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_operate_project
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 12 09:03:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_operate_project
     *
     * @mbggenerated Thu Apr 12 09:03:13 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}